services:
  trubit-web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: trubit-web
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
